"""Added monitored_urls table

Revision ID: v0.2
Revises: v0.1
Create Date: 2026-01-14 18:46:59.428302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v0.2'
down_revision: Union[str, Sequence[str], None] = 'v0.1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('check_interval_s', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_urls_url'), 'monitored_urls', ['url'], unique=True)
    op.create_index(op.f('ix_health_checks_created_at'), 'health_checks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_checks_created_at'), table_name='health_checks')
    op.drop_index(op.f('ix_monitored_urls_url'), table_name='monitored_urls')
    op.drop_table('monitored_urls')
    # ### end Alembic commands ###
