"""Scheduler support - Added scheduler_locks and additional columns to monitored_urls table

Revision ID: v0.2_2
Revises: v0.2
Create Date: 2026-01-15 10:04:43.040878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v0.2_2'
down_revision: Union[str, Sequence[str], None] = 'v0.2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_locks',
    sa.Column('monitored_url_id', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitored_url_id'], ['monitored_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitored_url_id')
    )
    op.create_index('idx_expires_at', 'scheduler_locks', ['expires_at'], unique=False)
    op.add_column('monitored_urls', sa.Column('next_check_at', sa.DateTime(), nullable=True))
    op.add_column('monitored_urls', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('monitored_urls', sa.Column('consecutive_failures', sa.Integer(), nullable=False))
    op.create_index('idx_active_next_check', 'monitored_urls', ['is_active', 'next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_active_next_check', table_name='monitored_urls')
    op.drop_column('monitored_urls', 'consecutive_failures')
    op.drop_column('monitored_urls', 'last_checked_at')
    op.drop_column('monitored_urls', 'next_check_at')
    op.drop_index('idx_expires_at', table_name='scheduler_locks')
    op.drop_table('scheduler_locks')
    # ### end Alembic commands ###
